service:
  name: 'Registration Nexi Adapter'
  # my own public URL, leave unset for the very basic mock used in unit tests
  # if nexi_downstream is set, this configures the webhook URL (and turns on requesting webhooks with payments)
  # if nexi_downstream is unset, this is mandatory, the base url used for built-in simulator payment links
  public_url: 'http://localhost:10000/paygatesrv' # do not add trailing /
  # base url of the attendee service, leave blank to use simple in-memory simulator (not useful for production)
  attendee_service: 'http://localhost:9091' # do not add trailing /
  # base url of the mail service, leave blank to use simple in-memory simulator (not useful for production)
  mail_service: 'http://localhost:9093' # no trailing slash
  # base url of the payment service, leave blank to use simple in-memory simulator (not useful for production)
  payment_service: 'http://localhost:9092' # do not add trailing /

  # base url for the Nexi downstream, leave blank to use the local simulator (should set public_url or generated paylinks will not work)
  # nexi_downstream: 'https://test.api.dibspayment.eu' (Test) or 'https://api.dibspayment.eu' (Live)

  # secret api key from nexi portal
  nexi_api_key: 'demosecret'

  # nexi merchant id
  nexi_merchant_id: 'GG1234_56789'

  # if set, will add these redirects to the request for the paylink
  success_redirect: 'http://localhost:10000/register'
  failure_redirect: 'http://localhost:10000/register'

  # the service will reject webhooks that reference another prefix (previous year expiry, etc.)
  transaction_id_prefix: "EF2024"

  # link to your terms of service, required
  terms_url: "https://example.com/legal/terms"
server:
  port: 9097
database:
  use: 'mysql' # or inmemory
  username: 'demouser'
  password: 'demopw'
  database: 'tcp(localhost:3306)/dbname'
  parameters:
    - 'charset=utf8mb4'
    - 'collation=utf8mb4_general_ci'
    - 'parseTime=True'
    - 'timeout=30s' # connection timeout
logging:
  severity: INFO
  # switch to true to log ALL communication from/to the payment provider (only signatures omitted)
  full_requests: false
  # set this to receive error notification mails if unexpected interaction with the payment provider occurs
  # error_notify_mail: nobody@example.com
security:
  fixed_token:
    api: 'put_secure_random_string_here_for_api_token'
    webhook: 'put_secure_random_string_here_for_webhook'
  cors:
    # set this to true to send disable cors headers - not for production - local/test instances only - will log lots of warnings
    disable: false
    # if setting disable_cors, you should also specify this
    allow_origin: 'http://localhost:8000'
invoice:
  title: Time Traveller Con 1969 Edition - Attendee Fee
  description: |
    Fee for attending Time Traveller Con 1969 Edition
    from July 17th to 22nd 1969, including all selected options.
    Accomodation and catgering will have been provided.
  purpose: Payment of entrance fee and options.